config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :artisans do
    resources :comments
    collection do
      get 'random'
    end
  end
  
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artisan.rb
class Artisan < ApplicationRecord
    has_many :comments
    validates :name, presence: true,
                    length: { minimum: 4 }
    validates :location, presence: true, 
                    length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :artisan
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_unleash_context
    private
    def set_posthog_context
      @posthog = PostHog::Client.new({
        api_key: "hrcY0WIICFwr5nXGlDTSndJwnZ1W1exrSb19h_wvVqQ",
        on_error: Proc.new { |status, msg| print msg }
      })
    end

    protect_from_forgery with: :exception
    before_action :set_raven_context

    private
    def set_raven_context
      Raven.extra_context(params: params.to_unsafe_h, url: request.url)
    end

    before_action :set_unleash_context

    private
    def set_unleash_context
      @unleash_context = Unleash::Context.new(
        session_id: session.id,
        remote_address: request.remote_ip,
        app_name: Rails.env,
        user_id: session[:user_id]
      )
    end

    before_action :set_tracing_context
    def set_tracing_context
      OpenTracing.global_tracer = Jaeger::Client.build(service_name: 'artisans', host: 'jaeger.kencjohnston.com')
    end
end

app/controllers/artisans_controller.rb
class ArtisansController < ApplicationController
    def index
        @artisans = Artisan.all
    end
    
    def show
        @artisan = Artisan.find(params[:id])
        Honeycomb.add_field("Artisan", @artisan.name)
        POSTHOG.capture({
            distinct_id: 'distinct id',
            event: 'Artisan Displayed',
            properties: {
                artisan_name: @artisan.name,
                artisan_id: @artisan.id
            }
        })
    end
    
    def random
        OpenTracing.start_span('random_artisan') do |scope|
            if UNLEASH.is_enabled? "random-artisan", @unleash_context
                @artisan = Artisan.all.sample  
            else
                @artisan = Artisan.first
            end
        end
    end

    def new
        @artisan = Artisan.new
    end
    
    def create
        @artisan = Artisan.new(artisan_params)

        if @artisan.save
            redirect_to @artisan
          else
            render 'new'
        end
    end

    def update
        @artisan = Artisan.find(params[:id])
       
        if @artisan.update(artisan_params)
          redirect_to @artisan
        else
          render 'edit'
        end
    end
    
    def edit
        @artisan = Artisan.find(params[:id])
    end

    def destroy
        @artisan = Artisan.find(params[:id])
        @artisan.destroy

        redirect_to artisans_path
    end

    private
        def artisan_params
            params.require(:artisan).permit(:name, :description, :location)
        end 
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @artisan = Artisan.find(params[:artisan_id])
        @comment = @artisan.comments.create(comment_params)
        redirect_to artisan_path(@artisan)
      end
     
      private
        def comment_params
          params.require(:comment).permit(:commenter, :body)
        end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def page_title(separator = " – ")
        [content_for(:title), 'Artisan World'].compact.join(separator)
      end
      
      def page_heading(title)
        content_for(:title){ title }
        content_tag(:h1, title)
      end
end

app/helpers/artisans_helper.rb
module ArtisansHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/artisans/_display.html.erb
<h2>
  <strong><%= @artisan.name %></strong>
</h2>
 
<p>
  <strong>Description:</strong> <%= @artisan.description %>
</p>

<p>
  <strong>Location:</strong> <%= @artisan.location %>
</p>

<%= link_to 'Back', artisans_path %>

app/views/artisans/_form.html.erb
<%= form_with(model: @artisan, local: true) do |form| %>
 
  <% if @artisan.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@artisan.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @artisan.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= form.label :location %><br>
    <%= form.text_area :location %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/artisans/edit.html.erb
<% page_heading "Edit "+@artisan.name %>
<h1>Edit artisan</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', artisans_path %>

app/views/artisans/index.html.erb
<% page_heading "List" %>
<h1>Listing artisans</h1>
 
 <%= link_to 'New', new_artisan_path %>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Location</th>
    <th colspan="3"></th>
  </tr>
 
  <% @artisans.each do |artisan| %>
    <tr>
      <td><%= artisan.name %></td>
      <td><%= artisan.description %></td>
      <td><%= artisan.location %></td>
      <td><%= link_to 'Show', artisan_path(artisan) %></td>
      <td><%= link_to 'Edit', edit_artisan_path(artisan) %></td>
      <td><%= link_to 'Remove', artisan_path(artisan),
              method: :delete, 
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

 <%= link_to 'Home', root_path %>

app/views/artisans/new.html.erb
<% page_heading "New" %>
<h1>New Artisan</h1>

<%= render 'form' %>

<%= link_to 'Back', artisans_path %>

app/views/artisans/random.html.erb
<% page_heading "Random" %>
<strong>RANDOM</strong>

<%= render 'display' %>

app/views/artisans/show.html.erb
<% page_heading @artisan.name %>
<%= render 'display' %>
<h2>Comments</h2>
<%= render @artisan.comments %>

<h2>Add a comment:</h2>
<%= form_with(model: [ @artisan, @artisan.comments.build ], local: true) do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/comments/_comment.html.erb
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>
 
  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= page_title %></title>
    <script src="https://t.posthog.com/static/array.js"></script>
    <script>
    posthog.init('hrcY0WIICFwr5nXGlDTSndJwnZ1W1exrSb19h_wvVqQ', {api_host: 'https://t.posthog.com'})
    </script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="header"><h1><%= link_to 'Artisan World', root_path %></h1></div>
    <div id="content"><%= yield %></div>
    <div id="footer">Written by <a href='https://gitlab.com/kencjohnston'>Kenny Johnston</a> | Environment: <%= Rails.env %></div>
  </body>
</html>

app/views/welcome/index.html.erb
<% page_heading "Home" %>
<h2>Welcome to Artisan World!</h2>
<h3>The Best Place on Earth</h3>
<p>Wonderful friends and family (and analysts), here are some useful links:</p>
<ul>
    <li><%= link_to 'All Artisans', artisans_path %></li>
    <li><%= link_to 'New Artisan', new_artisan_path %></li>
    <% if UNLEASH.is_enabled? "random-artisan", @unleash_context %>
    <li><%= link_to 'View a Random Artisan', random_artisans_path %></li>
    <% end %>
    <li><a href="https://gitlab.com/kencjohnston-apps/artisans">Review the Source for this Site</a></li>